### PR TITLE
remove firefox compatibility issue from readme

### PR DESCRIPTION
**Pull request by John-WL**

### CODE REVIEW

**Comment by ljleb** [comment]
What about dashing it instead of completely removing? It adds new information for people that have already seen the readme like that.

**Comment by John-WL** [comment]
I don't think we want to keep this info on the readme of the repo itself. I think the readme should be informative about the current state, not the past state of the repo

**Comment by John-WL** [comment]
We could add another tab for "fixed issues", but this would make even less sense than dashing it in my opinion

**Comment by John-WL** [comment]
Ideally, we want these issues to be resolved through prs so that people can easily see them as resolved, but firefox got fixed alomg the way I guess

**Comment by ljleb** [comment]
It really doesn't matter in the end. It's fine.

**Review by ljleb — APPROVED** [review]

**Pull request merged**
